workflows:
  ios-debug:
    name: iOS Debug Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    working_directory: playground/thai_idcard_reader_test
    environment:
      flutter: 3.38.9
      xcode: 16.2
      cocoapods: default
    scripts:
      - name: Debug working directory
        script: |
          echo "PWD: $(pwd)"
          ls -la
          echo "---"
          ls -la lib/ || echo "No lib/ directory"
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build debug iOS (no code signing)
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - playground/thai_idcard_reader_test/build/ios/iphoneos/*.app

  ios-release:
    name: iOS Release Build (Signed)
    max_build_duration: 30
    instance_type: mac_mini_m2
    working_directory: playground/thai_idcard_reader_test
    environment:
      flutter: 3.38.9
      xcode: 16.2
      cocoapods: default
      ios_signing:
        distribution_type: development
        bundle_identifier: org.nutchanon.thaiIdcardReaderTest
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Build release iOS
        script: |
          flutter build ipa --debug \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - playground/thai_idcard_reader_test/build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - life.particles@gmail.com
