workflows:
  ios-debug:
    name: iOS Debug Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: 3.24.0
      xcode: 15.4
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build debug iOS (no code signing)
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app

  ios-release:
    name: iOS Release Build (Signed)
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      flutter: 3.24.0
      xcode: 15.4
      cocoapods: default
      ios_signing:
        distribution_type: development
        bundle_identifier: com.example.thaiIdcardReaderTest
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Build release iOS
        script: |
          flutter build ipa --debug \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com  # Change this
